import Foundation

// Code from the system (decision DS2, DS3): every recipe role becomes one case of a generated modifier, and every
// foundation a named value, so a view writes `.buttonRole(.primary)` or `Space.group` and never a style or a number.
// Generated from templates in Hatch, so it costs no tokens; custom roles stay hand-written views the system points at.
// macOS 27 is the reference: glass styles are used as they are, and only when the app supports older systems does the
// code fall back (`if #available`) to the nearest older look.

public enum ComponentCodegen {
    public static let header = "// Generated by Hatch from components/system.json in the project notebook. Do not edit: change the system in Hatch."

    /// The files for the components folder, relative to it. A Swift package gets `Sources/<product>/…` (and a
    /// `Package.swift` when `makePackage` is set); a plain folder in the app gets the files at its root.
    public static func files(_ system: ComponentSystem, product: String?, makePackage: Bool = false) -> [String: String] {
        let dir = product.map { "Sources/\($0)/" } ?? ""
        var out = [
            dir + "Roles.swift": roles(system),
            dir + "Foundations.swift": foundations(system),
        ]
        if makePackage, let product { out["Package.swift"] = package(product: product, minimumMacOS: system.minimumMacOS) }
        return out
    }

    public static func package(product: String, minimumMacOS: String) -> String {
        """
        // swift-tools-version: 6.2
        \(header)
        import PackageDescription

        let package = Package(
            name: "\(product)",
            platforms: [.macOS("\(minimumMacOS)")],
            products: [.library(name: "\(product)", targets: ["\(product)"])],
            targets: [.target(name: "\(product)")]
        )

        """
    }

    // MARK: Roles

    public static func roles(_ s: ComponentSystem) -> String {
        var out = """
            \(header)
            // \(s.name), baseline v\(s.version). Roles: one element in one place for one purpose. Pick the role by element,
            // place and importance (components/README.md in the notebook); never style a control by hand.
            import SwiftUI

            /// The roles of \(s.name)'s design system.
            public enum Roles {

            """
        let generated = s.elementsUsed.compactMap { e -> (ComponentElement, [(String, ComponentRole, ComponentVariant?)])? in
            guard let element = ComponentElement.named(e) else { return nil }
            var cases: [(String, ComponentRole, ComponentVariant?)] = []
            for r in s.roles(of: e) where r.custom == nil || !r.recipe.isEmpty {
                guard isIdentifier(r.name) else { continue }
                cases.append((r.name, r, nil))
                for v in r.variants where isIdentifier(v.id) { cases.append((r.name + v.id.prefix(1).uppercased() + v.id.dropFirst(), r, v)) }
            }
            return cases.isEmpty ? nil : (element, cases)
        }
        for (element, cases) in generated {
            out += "    /// \(element.plural).\n    public enum \(typeName(element.id)): String, CaseIterable, Sendable {\n"
            for (name, role, variant) in cases {
                let doc = variant.map { "Variant \($0.id) of \(role.id): \($0.use)" } ?? "\(role.title): \(role.use)"
                out += "        /// \(oneLine(doc))\n        case \(name)\n"
            }
            out += "    }\n\n"
        }
        out += "}\n"

        for (element, cases) in generated {
            let type = typeName(element.id)
            out += "\npublic extension View {\n"
            out += "    /// Draws this \(element.title.lowercased()) as its role.\n"
            out += "    @ViewBuilder func \(element.id)Role(_ role: Roles.\(type)) -> some View {\n        switch role {\n"
            for (name, role, variant) in cases {
                var recipe = role.recipe
                if let variant { recipe.merge(variant.recipe) { $1 } }
                out += "        case .\(name):\n" + body(element: element, recipe: recipe, role: role, system: s, indent: "            ")
            }
            out += "        }\n    }\n}\n"
        }
        let custom = s.roles.filter { $0.custom != nil && $0.recipe.isEmpty }
        if !custom.isEmpty {
            out += "\n// Drawn by the app's own views, not generated:\n"
            for r in custom { out += "// - \(r.id): \(r.custom!)\n" }
        }
        return out
    }

    /// One case's modifiers, with an `if #available` fallback when it needs a newer macOS than the app supports.
    static func body(element: ComponentElement, recipe: [String: String], role: ComponentRole, system: ComponentSystem, indent: String) -> String {
        let (modern, notes) = modifiers(element: element, recipe: recipe, system: system, older: false)
        var out = notes.map { "\(indent)// \($0)\n" }.joined()
        let needsNew = modern.contains { $0.contains(".glass") }
        if needsNew && system.minimumMacOSNumber < 26 {
            let (older, _) = modifiers(element: element, recipe: recipe, system: system, older: true)
            out += "\(indent)if #available(macOS 26.0, *) {\n\(indent)    \(chain(modern))\n\(indent)} else {\n\(indent)    \(chain(older))\n\(indent)}\n"
        } else {
            out += "\(indent)\(chain(modern))\n"
        }
        _ = role
        return out
    }

    static func chain(_ modifiers: [String]) -> String { modifiers.isEmpty ? "self" : "self" + modifiers.joined() }

    /// The SwiftUI modifiers for a recipe, and notes for what a modifier cannot say (a tooltip's text, hover).
    /// `older` gives the look before macOS 26 (glass becomes bordered or a material).
    static func modifiers(element: ComponentElement, recipe r: [String: String], system: ComponentSystem, older: Bool) -> ([String], [String]) {
        var m: [String] = [], notes: [String] = []
        func glass(_ style: String) -> String {
            guard older else { return style }
            return ["glass": "bordered", "glassProminent": "borderedProminent"][style] ?? style
        }
        switch element.id {
        case "button":
            if let style = r["style"], style != "automatic" { m.append(".buttonStyle(.\(glass(style)))") }
            if let size = r["size"] { m.append(".controlSize(.\(size))") }
            if let label = r["label"] { m.append(".labelStyle(.\(label))") }
            if let shape = r["shape"], shape != "automatic" { m.append(".buttonBorderShape(.\(shape))") }
            if let tint = r["tint"], tint != "none" { m.append(".tint(\(color(tint, system)))") }
            if let key = r["key"], key != "none" { m.append(".keyboardShortcut(.\(key))") }
            if r["show"] == "onHover" { notes.append("Shown on hover or selection: the row decides when.") }
            if let tip = r["tooltip"], tip != "none" { notes.append(tip == "shortcut" ? "Tooltip: the title and the shortcut, with .help(…)." : "Tooltip: the title, with .help(…).") }
            if r["confirm"] == "yes" { notes.append("Confirm first: a confirmation dialog before it acts.") }
        case "menu":
            switch r["style"] {
            case "button": m.append(".menuStyle(.button)")
            case "borderlessButton": m.append(".menuStyle(.button)"); m.append(".buttonStyle(.borderless)")  // the macOS 12+ way
            default: break
            }
            if let look = r["look"], look != "automatic", r["style"] != "borderlessButton" { m.append(".buttonStyle(.\(glass(look)))") }
            if r["indicator"] == "hidden" { m.append(".menuIndicator(.hidden)") }
            if let label = r["label"] { m.append(".labelStyle(.\(label))") }
            if let size = r["size"] { m.append(".controlSize(.\(size))") }
        case "picker":
            if let style = r["style"], style != "automatic" { m.append(".pickerStyle(.\(style))") }
            if r["label"] == "hidden" { m.append(".labelsHidden()") }
            if let size = r["size"] { m.append(".controlSize(.\(size))") }
        case "toggle":
            if let style = r["style"], style != "automatic" { m.append(".toggleStyle(.\(style))") }
            if let size = r["size"] { m.append(".controlSize(.\(size))") }
        case "field":
            if let style = r["style"], style != "automatic" { m.append(".textFieldStyle(.\(style))") }
            if let size = r["size"] { m.append(".controlSize(.\(size))") }
        case "switcher":
            switch r["style"] {
            case "segmented", "menu": m.append(".pickerStyle(.\(r["style"]!))")
            case let other?: notes.append("\(other): drawn by the app's own view; as a Picker it falls back to segmented."); m.append(".pickerStyle(.segmented)")
            default: break
            }
            if let size = r["size"] { m.append(".controlSize(.\(size))") }
        case "row":
            let pad = ["compact": 2, "regular": 4, "airy": 8][r["density"] ?? "regular"] ?? 4
            m.append(".padding(.vertical, \(pad))")
            if r["separators"] == "hidden" { m.append(".listRowSeparator(.hidden)") }
            if r["actions"] == "onHover" { notes.append("Row actions show on hover or selection.") }
            if r["selection"] == "fill" { notes.append("Selection: a soft fill, drawn by the list.") }
        case "card":
            let radius = r["radius"].flatMap { $0 == "none" ? nil : value($0, system) } ?? "12"
            if let pad = r["padding"], pad != "none" { m.append(".padding(\(value(pad, system) ?? "16"))") }
            let shape = "RoundedRectangle(cornerRadius: \(radius), style: .continuous)"
            switch r["surface"] {
            case "grouped": m.append(".background(.background.secondary, in: \(shape))")
            case "bordered": m.append(".overlay(\(shape).strokeBorder(.separator))")
            case "material": m.append(".background(.regularMaterial, in: \(shape))")
            case "glass": m.append(older ? ".background(.regularMaterial, in: \(shape))" : ".glassEffect(.regular, in: \(shape))")
            default: break
            }
            if r["border"] == "hairline", r["surface"] != "bordered" { m.append(".overlay(\(shape).strokeBorder(.separator, lineWidth: 0.5))") }
            if r["shadow"] == "soft" { m.append(".shadow(color: .black.opacity(0.08), radius: 4, y: 1)") }
        case "sheet":
            let w = ["small": 360, "medium": 480, "large": 640][r["width"] ?? "medium"] ?? 480
            m.append(".frame(minWidth: \(w), idealWidth: \(w))")
            if r["footer"] == "spread" { notes.append("Footer: Cancel on the left, the main action on the right.") }
        case "badge":
            m.append(".font(.caption2.weight(.semibold))"); m.append(".monospacedDigit()")
            if r["style"] != "plain" {
                m.append(".foregroundStyle(.white)")
                m.append(".padding(.horizontal, 5)"); m.append(".padding(.vertical, 1)")
                m.append(".background(\(color(r["tint"] ?? "accent", system)), in: Capsule())")
            }
        case "toast":
            m.append(".padding(.horizontal, 14)"); m.append(".padding(.vertical, 8)")
            switch r["surface"] {
            case "glass": m.append(older ? ".background(.regularMaterial, in: Capsule())" : ".glassEffect(.regular, in: .capsule)")
            case "material": m.append(".background(.regularMaterial, in: Capsule())")
            default: m.append(".background(.background.secondary, in: Capsule())")
            }
            notes.append("Placed at the \(r["position"] ?? "bottom") of the window; \(r["duration"] ?? "short") on screen.")
        default:
            notes.append("Drawn by the app's own view.")
        }
        return (m, notes)
    }

    /// `critical` → `Palette.critical` when the system names it, else `.red`; a `color.*` foundation → `Palette.*`.
    static func color(_ tint: String, _ s: ComponentSystem) -> String {
        if tint.hasPrefix("color.") { return "Palette." + tint.dropFirst(6) }
        if tint == "critical" { return s.foundation("color.critical") != nil ? "Palette.critical" : "Color.red" }
        if tint == "accent" { return s.foundation("color.accent") != nil ? "Palette.accent" : "Color.accentColor" }
        return "Color.accentColor"
    }

    /// `space.group` → `Space.group`, `radius.card` → `Radius.card`.
    static func value(_ ref: String, _ s: ComponentSystem) -> String? {
        guard let f = s.foundation(ref) else { return nil }
        let name = String(ref.split(separator: ".", maxSplits: 1).last ?? "")
        switch f.kind {
        case .space: return "Space.\(name)"
        case .radius: return "Radius.\(name)"
        default: return nil
        }
    }

    // MARK: Foundations

    public static func foundations(_ s: ComponentSystem) -> String {
        var out = """
            \(header)
            // \(s.name)'s named values. Views use these, never a color, size or spacing number.
            import SwiftUI
            import AppKit

            """
        func section(_ kind: ComponentFoundation.Kind, _ type: String, _ doc: String, _ value: (ComponentFoundation) -> String?) {
            let list = s.foundations.filter { $0.kind == kind }
            guard !list.isEmpty else { return }
            out += "\n/// \(doc)\npublic enum \(type) {\n"
            for f in list {
                let name = String(f.id.split(separator: ".", maxSplits: 1).last ?? "")
                guard isIdentifier(name), let v = value(f) else { continue }
                out += "    /// \(oneLine(f.use))\n    public static let \(name)\(kind == .space || kind == .radius ? ": CGFloat" : "") = \(v)\n"
            }
            out += "}\n"
        }
        section(.color, "Palette", "Colors by what they are for.") { f in
            if let light = f.light.flatMap(hex) { return "Color(light: \(light), dark: \(f.dark.flatMap(hex) ?? light))" }
            return f.system.map(systemColor)
        }
        section(.text, "Typography", "Text styles by what they are for; they follow Dynamic Type.") { f in
            let design = f.design.map { ", design: .\($0)" } ?? ""
            let weight = f.weight.map { ", weight: .\($0)" } ?? ""
            if let style = f.system { return "Font.system(.\(style)\(design)\(weight))" }
            if let size = f.value { return "Font.system(size: \(ComponentRole.number(size))\(weight)\(design))" }
            return nil
        }
        section(.space, "Space", "Spacing by what it separates.") { f in f.value.map { ComponentRole.number($0) } }
        section(.radius, "Radius", "Corner radii by what they round.") { f in f.value.map { ComponentRole.number($0) } }
        if s.foundations.contains(where: { $0.kind == .color && $0.light != nil }) {
            out += """

                extension Color {
                    /// A color with its own light and dark values.
                    init(light: UInt32, dark: UInt32) {
                        self.init(nsColor: NSColor(name: nil) { appearance in
                            let hex = appearance.bestMatch(from: [.darkAqua, .aqua]) == .darkAqua ? dark : light
                            return NSColor(srgbRed: CGFloat((hex >> 16) & 0xFF) / 255, green: CGFloat((hex >> 8) & 0xFF) / 255,
                                           blue: CGFloat(hex & 0xFF) / 255, alpha: 1)
                        })
                    }
                }

                """
        }
        return out
    }

    /// `#3366CC` → `0x3366CC` (alpha is dropped: the system decides transparency through materials).
    static func hex(_ s: String) -> String? {
        let digits = s.dropFirst().prefix(6)
        return digits.count == 6 && digits.allSatisfy(\.isHexDigit) ? "0x" + digits.uppercased() : nil
    }

    /// `accentColor` → `.accentColor`; `windowBackgroundColor`, `systemRed` → AppKit's dynamic color; `red` → `.red`.
    static func systemColor(_ name: String) -> String {
        if name == "accentColor" { return "Color.accentColor" }
        if name.hasPrefix("system") || name.hasSuffix("Color") { return "Color(nsColor: .\(name))" }
        return "Color.\(name)"
    }

    static func typeName(_ element: String) -> String { element.prefix(1).uppercased() + element.dropFirst() }

    static func isIdentifier(_ s: String) -> Bool {
        guard let first = s.first, first.isLetter || first == "_" else { return false }
        return s.allSatisfy { $0.isLetter || $0.isNumber || $0 == "_" } && !["default", "case", "self", "true", "false", "nil"].contains(s)
    }

    static func oneLine(_ s: String) -> String { s.replacingOccurrences(of: "\n", with: " ") }
}
