/* wire thumbnails: [x,y,w,h,cls] in a 100x64 box */
const WIRES={
 three:[[2,2,20,60],[24,2,34,60,'f'],[60,2,38,60,'a']],
 stageFirst:[[2,2,96,7],[2,11,96,38,'f'],[2,51,44,11],[50,51,48,11,'a']],
 stacked:[[2,2,96,36,'f'],[2,40,96,22,'a']],
 listDetail:[[2,2,34,60],[38,2,60,60,'a']],
 listFull:[[2,2,96,60,'f']],
 grid3:[[2,10,30,50,'f'],[35,10,30,50,'f'],[68,10,30,50,'a']],
 overlay:[[8,8,58,44,'f'],[30,16,58,44,'a']],
 flip:[[8,6,84,46,'f'],[2,56,96,6,'a']],
 filmstrip:[[2,2,96,40,'f'],[2,46,22,16],[26,46,22,16,'a'],[50,46,22,16],[74,46,22,16]],
 tabs:[[2,2,96,8],[2,12,96,50,'f']],
 oneScroll:[[2,2,96,14,'f'],[2,18,96,20],[2,40,96,22]],
 split2:[[2,2,60,60,'f'],[64,2,34,60,'a']],
 wizard:[[2,2,96,6],[14,12,72,40,'f'],[60,54,26,8,'a']],
 sheet:[[2,2,96,60],[18,14,64,36,'a']],
 board5:[[2,4,17,56,'f'],[21,4,17,56],[40,4,17,56,'a'],[59,4,17,56],[78,4,17,56]],
 cols15:[[1,4,6,56],[8,4,6,56],[15,4,6,56],[22,4,6,56],[29,4,6,56],[36,4,6,56],[43,4,6,56],[50,4,6,56],[57,4,6,56],[64,4,6,56],[71,4,6,56],[78,4,6,56],[85,4,6,56],[92,4,6,56]],
 rows:[[2,2,96,8,'f'],[2,12,96,8],[2,22,96,8],[2,32,96,8],[2,42,96,8],[2,52,96,8]],
 chat:[[2,2,60,60,'f'],[64,2,34,60,'a']],
 popup:[[2,2,28,8,'a'],[2,12,28,48,'f'],[34,2,64,60]],
 palette:[[18,8,64,10,'a'],[18,20,64,8],[18,30,64,8],[18,40,64,8]],
 steps:[[2,4,60,8,'f'],[2,16,60,8,'f'],[2,28,60,8,'a'],[2,40,60,8],[2,52,60,8],[66,4,32,56]],
 cards:[[2,4,30,26,'f'],[35,4,30,26,'f'],[68,4,30,26,'a'],[2,34,30,26],[35,34,30,26]],
};
const DECISIONS=[
/* ---------- A FOUNDATIONS ---------- */
{id:'A1',sec:'foundations',title:'Which ticket types should exist?',
 q:'The types decide which screens, statuses and agent instructions exist. Fewer types are simpler to learn, more types make each one sharper.',
 opts:[
  {k:'A',n:'Six types',d:'Question, Sketch, Proposal, Tweak, Bug, Theme.'},
  {k:'B',n:'Three types',d:'Discuss, Design, Fix. Sketch and Proposal become two modes of Design.'},
  {k:'C',n:'One type plus labels',d:'Every ticket is the same, labels say what it is.'}],
 rec:'A',why:'Each of the six has a different path and a different main screen. A Sketch needs no Swift and a Proposal does, and you asked for exactly that split. With three types the difference hides inside a mode, and with one type the agent has to remember the rules for each label.'},
{id:'A2',sec:'foundations',title:'What should the old "Round" be called?',
 q:'The Swift-specimen comparison with options is the heart of Echo Labs today.',
 opts:[{k:'A',n:'Proposal',d:'"Proposal #151, 3 options".'},{k:'B',n:'Trial',d:'Suggests testing options out.'},{k:'C',n:'Study',d:'A design word, less clear for newcomers.'},{k:'D',n:'Keep "Round"',d:'No migration of vocabulary.'}],
 rec:'A',why:'It reads naturally in a sentence and states what the ticket is for: something proposed that you judge. "Round" says nothing to a new agent or a new project, and "Trial" implies the change is being tested rather than chosen.'},
{id:'A3',sec:'foundations',title:'How should tickets be numbered?',
 q:'GitHub gives every issue a number in its repo.',
 opts:[{k:'A',n:'Plain #151',d:'The GitHub issue number, project shown as a chip.'},{k:'B',n:'Project prefix',d:'ECHO-151, with the project name in the ID.'},{k:'C',n:'Own counter',d:'Hatch numbers tickets itself.'}],
 rec:'A',why:'The number is the one thing you cannot change on GitHub, so using it directly means no mapping table and no way for the two to disagree. One shared tickets repo keeps numbers unique across projects. A prefix is easy to add later as display only.'},
{id:'A4',sec:'foundations',title:'How many statuses?',
 q:'Every status must say whose turn it is. The Desk sorts on that.',
 opts:[{k:'A',n:'16 statuses in 5 phases',d:'Draft to Done, grouped as Intake, Exploring, Building, Landed, Off.'},{k:'B',n:'8 coarse statuses',d:'Merges agent and your turns into the same status.'},{k:'C',n:'Different statuses per type',d:'Each type has its own list.'}],
 rec:'A',why:'The Desk needs to know who has the ball, so your turn and the agent\'s turn cannot share a status. The 5 phases keep the Board readable even though there are 15 statuses. Per-type lists would mean learning six vocabularies.'},
{id:'A5',sec:'foundations',title:'How should "whose turn" be shown?',
 q:'This appears on rows, cards, banners and the Board.',
 opts:[{k:'A',n:'Colour plus text',d:'Amber for you, teal for agents, slate for Hatch, green finished, grey paused. The status name always sits beside the colour.'},{k:'B',n:'Avatars',d:'A small avatar for the person or agent holding the ticket.'},{k:'C',n:'Position only',d:'No colour, only the grouping on the Desk.'}],
 rec:'A',why:'Colour is read at a glance in a long list, and the text beside it keeps it usable without relying on colour alone. Avatars suit teams, and this is a one-person tool with agents.'},
{id:'A6',sec:'foundations',title:'How do type, status and project appear on GitHub?',
 q:'Tickets are GitHub issues in a private repo.',
 opts:[{k:'A',n:'Labels',d:'type:proposal, status:your-call, project:echo.'},{k:'B',n:'GitHub Projects fields',d:'Custom fields on a project board.'},{k:'C',n:'Issue types',d:'Native issue types, where the repo supports them.'}],
 rec:'A',why:'Labels work in every repo, in the list view, on the phone and through the plain API. Projects fields need a separate API and extra sync. Native issue types depend on the repo being owned by an organization, so I would use them only for the type, later, if you move.'},

/* ---------- B SHELL ---------- */
{id:'B1',sec:'shell',title:'How is the sidebar organized?',
 q:'The sidebar is the map of the whole app.',
 opts:[
  {k:'A',n:'Work and reference groups',d:'Desk, Tickets, Board, Previews on top. Specs, Decisions on a second group. Agents, Log at the bottom.',w:'popup'},
  {k:'B',n:'Few sections, views inside',d:'Desk and Tickets only. Board and Previews become views inside Tickets.',w:'listDetail'},
  {k:'C',n:'Top tabs',d:'A tab bar instead of a sidebar.',w:'tabs'}],
 rec:'A',why:'You move between Desk, Board and Previews several times a day, so they should be one click away. The groups separate things you act on from things you look up. It also matches Echo\'s own sidebar conventions on macOS.'},
{id:'B2',sec:'shell',title:'How do you switch project?',
 q:'Echo is the first project, others will follow.',
 opts:[{k:'A',n:'Popup at the top of the sidebar',d:'Shows project and branch. Includes "All projects".'},{k:'B',n:'One window per project',d:'Each project opens its own window.'},{k:'C',n:'Projects as sidebar sections',d:'Every project expands in the same sidebar.'}],
 rec:'A',why:'It keeps one window and one Desk across projects, which matters because "your turn" does not care which project a ticket belongs to. Separate windows split your attention, and expanding every project in the sidebar gets long quickly.'},
{id:'B3',sec:'shell',title:'What does the Desk show when you have several projects?',
 q:'',
 opts:[{k:'A',n:'Everything, with a project chip',d:'All projects at once, filter available.'},{k:'B',n:'Current project only',d:'Switch project to see another Desk.'}],
 rec:'A',why:'Your turn is your turn. If a Question in another project waits for you, hiding it behind a switch is how tickets get forgotten. A filter handles the day you want to focus.'},
{id:'B4',sec:'shell',title:'Where does "Ask Hatch" live?',
 q:'A way to ask Claude about the current ticket or screen without leaving it.',
 opts:[{k:'A',n:'Side panel',d:'Opens on the right, keeps the current ticket as context. Toggle with a shortcut.',w:'chat'},{k:'B',n:'Separate window',d:'A floating chat window.'},{k:'C',n:'Only inside tickets',d:'Via the thread of each ticket.'}],
 rec:'A',why:'The panel lets you look at the specimen and talk about it at the same time. A separate window loses the context, and thread-only misses the questions that are not about one ticket. Everything asked in the panel about a ticket is also saved to its thread.'},
{id:'B5',sec:'shell',title:'How is sync with GitHub shown?',
 q:'Sync is automatic, but you should know when it is not working.',
 opts:[{k:'A',n:'Footer status plus Log',d:'A small status at the bottom of the sidebar, details in Log, a banner only when something fails.'},{k:'B',n:'Toolbar badge',d:'A sync icon in the toolbar.'},{k:'C',n:'Hidden',d:'Only visible in the Log.'}],
 rec:'A',why:'It is always visible without taking toolbar space. A failure becomes a banner you cannot miss, which matters because a failed sync means GitHub and Hatch disagree.'},
{id:'B6',sec:'shell',title:'How do you get notified?',
 q:'Agents work while you are elsewhere.',
 opts:[{k:'A',n:'Dock badge plus macOS notification',d:'Badge counts your-turn tickets. Notification when something new needs you, grouped.'},{k:'B',n:'Badge only',d:'No notifications.'},{k:'C',n:'Email or push',d:'Through GitHub.'}],
 rec:'A',why:'The badge is the quiet default and the notification is what pulls you back when a Proposal is ready. GitHub notifications can still be turned on separately for the phone.'},

/* ---------- C DESK ---------- */
{id:'C1',sec:'desk',title:'What is the Desk layout?',
 q:'The old Inbox used a list and a reading pane. For judging work the reading pane was too small to be useful.',
 opts:[
  {k:'A',n:'List and brief, open takes the window',d:'The right pane is a short brief. Return opens the ticket full width.',w:'listDetail'},
  {k:'B',n:'Classic three panes',d:'Sidebar, list and a large reading pane that shows the work itself.',w:'three'},
  {k:'C',n:'One card at a time',d:'Triage mode: a single large card, next and previous.',w:'sheet'}],
 rec:'A',why:'The Desk exists to decide what to do next. The actual judging needs the full window anyway, so squeezing it into a pane serves neither job. The brief pane still tells you how big the task is before you open it.'},
{id:'C2',sec:'desk',title:'How is the Desk grouped?',
 q:'',
 opts:[{k:'A',n:'By what is needed from you',d:'Your call, Needs answers, To verify, then Waiting on agents.'},{k:'B',n:'By project',d:'One group per project.'},{k:'C',n:'By age',d:'Oldest first, one list.'}],
 rec:'A',why:'The groups map to different kinds of effort: judge, answer, verify. You can do them in batches. Age is shown on each row, so you can still spot what has waited longest.'},
{id:'C3',sec:'desk',title:'What does each Desk row show?',
 q:'',
 opts:[{k:'A',n:'Type, number, title, what to do and how long it takes',d:'Plus project chip and age. For Proposals, the recommendation.'},{k:'B',n:'Title only',d:'Minimal.'},{k:'C',n:'With thumbnails',d:'A small preview of the options in the row.'}],
 rec:'A',why:'"What to do and about how long" is what lets you choose between ten items. Thumbnails look nice but add cost on every row and are too small to judge, so they belong in the brief pane.'},
{id:'C4',sec:'desk',title:'What about tickets waiting on agents?',
 q:'',
 opts:[{k:'A',n:'Collapsed group at the bottom',d:'With a count, expand when you want.'},{k:'B',n:'Only on the Board',d:'Not on the Desk at all.'},{k:'C',n:'Always expanded',d:'Everything visible.'}],
 rec:'A',why:'You want to know that work is happening, but it should never push your own tickets out of sight. Collapsed with a count gives you both.'},
{id:'C5',sec:'desk',title:'How much can you do from the Desk list itself?',
 q:'Keyboard triage is fast, but a decision made without seeing the options is risky.',
 opts:[{k:'A',n:'Navigate, open, park, drop',d:'Decisions are made inside the ticket.'},{k:'B',n:'Full triage',d:'Accept the recommendation straight from the list.'},{k:'C',n:'Mouse only',d:'No keyboard shortcuts.'}],
 rec:'A',why:'Accepting triggers an agent run that costs tokens and time, so it should follow a look at the options. Parking and dropping are safe to do from the list.'},
{id:'C6',sec:'desk',title:'What does an empty Desk show?',
 q:'',
 opts:[{k:'A',n:'All clear plus what agents are doing',d:'A calm message and a summary of running work.'},{k:'B',n:'Plain empty state',d:'Just "nothing to do".'},{k:'C',n:'Suggestions',d:'Prompts to create tickets or revisit parked ones.'}],
 rec:'A',why:'Knowing that three agents are building is what makes "nothing for you" reassuring instead of suspicious. Parked tickets are linked at the bottom without pushing them.'},

/* ---------- D TICKETS ---------- */
{id:'D1',sec:'tickets',title:'What does the Tickets screen look like?',
 q:'',
 opts:[{k:'A',n:'Table with filters and saved views',d:'Columns for type, status, turn, project, age. Toggle to group by Theme.',w:'rows'},{k:'B',n:'Outline by Theme',d:'Themes expand into their children.',w:'oneScroll'},{k:'C',n:'Cards',d:'A grid of ticket cards.',w:'cards'}],
 rec:'A',why:'You will search and sort a lot, and a table is the clearest way to do that. The Theme grouping is one toggle away when you want the outline view.'},
{id:'D2',sec:'tickets',title:'How are the Board columns defined?',
 q:'',
 opts:[{k:'A',n:'Five phases',d:'Intake, Exploring, Building, Landed, Off. Cards show their exact status chip.',w:'board5'},{k:'B',n:'One column per status',d:'Sixteen columns.',w:'cols15'},{k:'C',n:'Swimlanes by project',d:'Rows per project, columns by phase.',w:'rows'}],
 rec:'A',why:'Sixteen columns do not fit on a window, and the phases tell the story of where work is. The chip on each card keeps the detail. Swimlanes can be added once there are several active projects.'},
{id:'D3',sec:'tickets',title:'How do filters and saved views work?',
 q:'',
 opts:[{k:'A',n:'Token filter bar plus saved views',d:'type:bug status:to-verify, saved by name in the sidebar.'},{k:'B',n:'Sidebar filters',d:'Checkboxes in a panel.'},{k:'C',n:'Search only',d:'Type words.'}],
 rec:'A',why:'Token filters are fast with the keyboard and map directly to the SQLite columns and GitHub labels. Saved views give you "Everything waiting on agents" in one click.'},
{id:'D4',sec:'tickets',title:'What does a Theme (parent ticket) look like?',
 q:'',
 opts:[{k:'A',n:'Progress header and child list',d:'"3 of 7 done", children grouped by phase.'},{k:'B',n:'Tree',d:'A nested tree on the Tickets screen only.'}],
 rec:'A',why:'A Theme is a place to see how a body of work is going, so progress comes first. The tree is still available as the grouped view of the Tickets table.'},

/* ---------- E COMPOSE ---------- */
{id:'E1',sec:'compose',title:'How do you create a ticket?',
 q:'',
 opts:[{k:'A',n:'One form with a check panel',d:'Type, title, description, screenshots, links. Hatch check on the right. A quick-capture shortcut makes a Draft with only a title.',w:'split2'},{k:'B',n:'Step-by-step wizard',d:'One question per step.',w:'wizard'},{k:'C',n:'Quick capture only',d:'A title and a screenshot, Hatch asks the rest.',w:'sheet'}],
 rec:'A',why:'You can see everything at once and fill what you know. The quick-capture shortcut covers the case where you only have time for a line and a screenshot, and Hatch then asks for the rest.'},
{id:'E2',sec:'compose',title:'When does the check run?',
 q:'Free local search can run while you type. The agent check costs tokens.',
 opts:[{k:'A',n:'Local search while typing, agent check on Submit',d:'Related tickets and Spec items appear instantly. Questions come after you submit.'},{k:'B',n:'Agent check while typing',d:'Questions appear as you write.'},{k:'C',n:'Manual "Check" button',d:'Only when you press it.'}],
 rec:'A',why:'It gives you the useful hints for free and spends tokens only once, on a ticket you decided to send. Checking while typing would re-run the agent on every pause.'},
{id:'E3',sec:'compose',title:'How do screenshots get into a ticket?',
 q:'',
 opts:[{k:'A',n:'Drop or paste, capture the Echo window, simple annotation',d:'Box, arrow and note on the image.'},{k:'B',n:'Drop or paste only',d:'Annotate in another app.'},{k:'C',n:'Capture only',d:'Window capture, nothing else.'}],
 rec:'A',why:'Pointing at the exact element is what makes a screenshot useful to an agent, and capture-and-mark is the fastest way to do that. The annotation is only three tools, so it is small to build.'},
{id:'E4',sec:'compose',title:'How do the agent\'s questions reach you?',
 q:'',
 opts:[{k:'A',n:'Answer cards in the ticket',d:'Each question has suggested answers as buttons and a free text field. They also appear on the Desk.'},{k:'B',n:'Comments only',d:'Questions are posted as thread comments.'},{k:'C',n:'A dialog',d:'A modal shows all questions.'}],
 rec:'A',why:'Structured answers are what lets the agent read your reply exactly. Suggested answers make most questions one click. Everything is mirrored to the GitHub thread for the record.'},
{id:'E5',sec:'compose',title:'Which kinds of links exist between tickets?',
 q:'',
 opts:[{k:'A',n:'Five kinds',d:'Related, Parent (Theme), Blocks, Duplicates, Supersedes.'},{k:'B',n:'Three kinds',d:'Related, Parent, Blocks.'},{k:'C',n:'Free text',d:'Mention #numbers.'}],
 rec:'A',why:'Supersedes matters here: a new decision that replaces an old one should say so, so the old Spec item is flagged. Duplicates lets the check offer to merge. Both are small to add and hard to reconstruct later.'},
{id:'E6',sec:'compose',title:'What happens when the check finds a likely duplicate?',
 q:'',
 opts:[{k:'A',n:'Offer Merge, Link, or Keep separate',d:'You decide.'},{k:'B',n:'Close automatically',d:'The newer ticket is closed.'}],
 rec:'A',why:'Similar is not the same. A new ticket may be about the same area but a different change, and closing it silently would lose that.'},
{id:'E7',sec:'compose',title:'Should each type have a template?',
 q:'',
 opts:[{k:'A',n:'Required fields per type',d:'Bug: steps, expected, actual. Tweak: element and change. Sketch: goal and constraints. Proposal: what, why, scope.'},{k:'B',n:'One free-form body',d:'Write what you like.'}],
 rec:'A',why:'The fields are what the agent will ask about anyway. Having them in the form means fewer round trips. You can leave a field short, and Hatch will ask only about what is missing.'},
];
