DECISIONS.push(
/* ---------- F TICKET VIEW ---------- */
{id:'F1',sec:'ticket',title:'How is a ticket page structured?',
 q:'',
 opts:[{k:'A',n:'Header and banner, then tabs',d:'Overview, Options (or Variants), Thread, Work, History.',w:'tabs'},{k:'B',n:'One long scroll',d:'All sections on one page.',w:'oneScroll'},{k:'C',n:'Thread always visible',d:'Main content left, thread always on the right.',w:'split2'}],
 rec:'A',why:'Each tab is a different kind of work: judging, discussing, watching a build. Tabs keep the Options tab free for the full width the stage needs. The thread is one click away, and the banner always shows what is expected.'},
{id:'F2',sec:'ticket',title:'How prominent is "whose turn it is"?',
 q:'',
 opts:[{k:'A',n:'A banner with the main action',d:'A coloured bar at the top: what is expected, and the button for it.'},{k:'B',n:'A status chip only',d:'Small chip in the header.'}],
 rec:'A',why:'The most common question on opening a ticket is "what do I do here". A banner answers it with a button, so you do not hunt for the next step.'},
{id:'F3',sec:'ticket',title:'How is the thread shown?',
 q:'GitHub comments, agent messages and system events all belong to the ticket.',
 opts:[{k:'A',n:'One timeline with filters',d:'Comments, agent messages and events together. Toggle events on or off.'},{k:'B',n:'Separate Thread and History tabs',d:'Conversation apart from system events.'}],
 rec:'A',why:'The order of events is the story, for example "you sent it back, then rev 2 arrived". Filters give the clean conversation view when you want it.'},
{id:'F4',sec:'ticket',title:'How do you talk to the agent from a ticket?',
 q:'A comment from you can mean different things.',
 opts:[{k:'A',n:'Three message kinds: Note, Ask, Instruction',d:'Note adds context. Ask expects an answer and moves the turn to the agent. Instruction changes the work.'},{k:'B',n:'A single comment box',d:'The agent decides what you meant.'}],
 rec:'A',why:'The kind decides what Hatch does next, so it should not be guessed. An Ask moves the turn, a Note does not, and an Instruction creates a revision. That is code, not agent memory.'},
{id:'F5',sec:'ticket',title:'How much history do you see?',
 q:'',
 opts:[{k:'A',n:'Every event in History',d:'Status changes, picks, syncs, commits, token use. Searchable.'},{k:'B',n:'Status changes only',d:'A short list.'}],
 rec:'A',why:'It is already recorded in SQLite, so showing it costs nothing, and it is the answer to "why is this in that status" and "did that reach GitHub".'},

/* ---------- G SKETCH ---------- */
{id:'G1',sec:'sketch',title:'How are variants arranged?',
 q:'',
 opts:[{k:'A',n:'Side by side, with a one-at-a-time mode',d:'Up to three in a row, a carousel for more.',w:'grid3'},{k:'B',n:'Carousel only',d:'One variant at a time.',w:'flip'},{k:'C',n:'Stacked list',d:'Variants one below the other.',w:'rows'}],
 rec:'A',why:'You choose by comparing, and side by side is the quickest way to compare layouts. The one-at-a-time mode covers four or more variants and detail checks.'},
{id:'G2',sec:'sketch',title:'How do you give feedback on a variant?',
 q:'',
 opts:[{k:'A',n:'Pinned comments',d:'Click on the variant to drop a numbered pin with a note.'},{k:'B',n:'A note per variant',d:'One text box under each variant.'},{k:'C',n:'Rating',d:'Stars or thumbs.'}],
 rec:'A',why:'"Too much scrolling here" is more useful to an agent than "B is worse". The pin records the position, and you can still add a general note per variant.'},
{id:'G3',sec:'sketch',title:'How are Sketches drawn?',
 q:'No Swift is compiled for a Sketch.',
 opts:[{k:'A',n:'HTML styled like macOS, clearly marked as a concept',d:'Appears in seconds, cheap in tokens.'},{k:'B',n:'Static images',d:'Generated pictures.'},{k:'C',n:'SwiftUI right away',d:'No Sketch type, only Proposals.'}],
 rec:'A',why:'It answers the layout and flow questions without a compile, which is the point of a Sketch. The Concept label is permanent so nobody mistakes it for a faithful render.'},
{id:'G4',sec:'sketch',title:'How does a Sketch end?',
 q:'',
 opts:[{k:'A',n:'Choose a direction, mix parts, Make it real',d:'"Header from A, list from C". Make it real creates a Proposal or Tweak, prefilled.'},{k:'B',n:'Pick one variant',d:'The chosen variant is the result.'}],
 rec:'A',why:'Real choices mix: you like the header of one and the list of another. A recorded mix gives the next ticket a precise starting point.'},

/* ---------- I BUILD ---------- */
{id:'I1',sec:'build',title:'How is a build shown?',
 q:'',
 opts:[{k:'A',n:'Steps with results and a live log',d:'Plan, Claim, Implement, Build, Tests, Match check, Ready.',w:'steps'},{k:'B',n:'Status and log only',d:'A chip and a text stream.',w:'rows'}],
 rec:'A',why:'You can see in one glance where it is and where it failed. The log stays one click away for details.'},
{id:'I2',sec:'build',title:'When must you approve the agent\'s plan?',
 q:'The plan lists the files it will touch and the tests it will run.',
 opts:[{k:'A',n:'Only for Bugs and large changes',d:'Auto-proceeds for accepted Proposals and Tweaks. Asks when more than a set number of files.'},{k:'B',n:'Always',d:'Every build waits for you.'},{k:'C',n:'Never',d:'Plan is shown, not approved.'}],
 rec:'A',why:'An accepted Proposal already says what to build, so asking again is friction. A Bug fix or a plan that spreads over many files is where surprises happen, so that is where you get a say.'},
{id:'I3',sec:'build',title:'Which tests run?',
 q:'',
 opts:[{k:'A',n:'Tests mapped to the area; the repo\'s CI runs the full suite',d:'The project config says which test plan belongs to which area. Hatch runs only that in the ticket\'s workspace. The full suite is left to CI (see I6).'},{k:'B',n:'Always the full suite',d:'Every ticket.'},{k:'C',n:'None until merge',d:'Only build.'}],
 rec:'A',why:'It keeps the loop fast while you iterate. You said the testing must stay limited, and that the repo should cover the rest, so Hatch does not run a full build before merge. CI does that (see I6).'},
{id:'I4',sec:'build',title:'How is the Match check shown?',
 q:'',
 opts:[{k:'A',n:'Parts table plus image comparison',d:'Per part pass or fail, and the accepted | Echo | diff image for each state.'},{k:'B',n:'Pass or fail only',d:'A single result.'}],
 rec:'A',why:'It is the evidence that Echo looks like what you accepted. If it fails, you want to see which part and how far off.'},
{id:'I5',sec:'build',title:'What can you do while an agent is working?',
 q:'',
 opts:[{k:'A',n:'Stop, take over in Terminal or Xcode, send an instruction',d:'Take over opens the workspace.'},{k:'B',n:'Stop only',d:'End the run.'}],
 rec:'A',why:'Sometimes you want to finish the last bit yourself. Because each ticket has its own workspace, handing it to you does not disturb any other agent.'},

/* ---------- J PREVIEW ---------- */
{id:'J1',sec:'preview',title:'How do tickets get into a Preview?',
 q:'',
 opts:[{k:'A',n:'You select them',d:'Checkboxes on Previews. Hatch builds that set.'},{k:'B',n:'Automatic',d:'Everything To verify is merged into one Preview.'},{k:'C',n:'One Preview per ticket',d:'Separate builds.'}],
 rec:'A',why:'You choose what you want to look at together, and a ticket that is not ready stays out. Automatic previews change under you, and per-ticket builds are the slow thing you wanted to avoid.'},
{id:'J2',sec:'preview',title:'What happens when two tickets conflict?',
 q:'',
 opts:[{k:'A',n:'Tell you which pair, offer drop, stack or ask the agent to resolve',d:''},{k:'B',n:'Fail the build',d:'Show an error.'}],
 rec:'A',why:'A conflict is information about which tickets overlap. Naming the pair and offering the next step turns an error into a decision.'},
{id:'J3',sec:'preview',title:'How do you verify?',
 q:'',
 opts:[{k:'A',n:'Per ticket: Looks right or Needs work',d:'With a checklist of what to look at, notes and screenshots.'},{k:'B',n:'Approve all',d:'One button for the whole Preview.'}],
 rec:'A',why:'You will often find two good and one wrong. Per-ticket verdicts let the good ones merge while the third goes back. The checklist comes from the accepted option so you know what to look at.'},
{id:'J4',sec:'preview',title:'How does the Preview app run?',
 q:'The Preview is a separate build of Echo.',
 opts:[{k:'A',n:'A separate copy, labelled Preview 03',d:'Runs next to your normal Echo. A banner in the window says it is a Preview.'},{k:'B',n:'Replaces your running Echo',d:'Quit and relaunch.'}],
 rec:'A',why:'You can compare with the Echo you use every day and nothing you rely on is replaced. The banner needs a small DEBUG addition in Echo.'},
{id:'J5',sec:'preview',title:'How are approved tickets merged?',
 q:'',
 opts:[{k:'A',n:'Merge plan shown first, one button',d:'Design system first, tag, then Echo bumps and merges.'},{k:'B',n:'Manual',d:'You merge each branch yourself.'}],
 rec:'A',why:'The order matters and is easy to get wrong by hand. Showing the plan first keeps you in control, and one button does the safe sequence.'},
{id:'J6',sec:'preview',title:'What if one ticket in a Preview fails?',
 q:'',
 opts:[{k:'A',n:'Others still merge',d:'The failed one goes to Fixing.'},{k:'B',n:'All or nothing',d:'The Preview is rejected.'}],
 rec:'A',why:'Tickets are independent changes. Holding good ones back for a bad one only slows you down. The merge plan is recomputed without the failed ticket.'},

/* ---------- K AGENTS ---------- */
{id:'K1',sec:'agents',title:'Is there an Agents screen?',
 q:'',
 opts:[{k:'A',n:'Yes: runs, claims, queue and cost',d:'One table of running work with queue and claims.'},{k:'B',n:'Only inside tickets',d:'No overview.'}],
 rec:'A',why:'With several agents in parallel you need one place that shows what is running, what is waiting for files, and what it costs. It is also where conflicts are resolved.'},
{id:'K2',sec:'agents',title:'How many agents run at once?',
 q:'',
 opts:[{k:'A',n:'Default 3, configurable',d:'Slots shown on the Agents screen.'},{k:'B',n:'Unlimited',d:'Start everything.'},{k:'C',n:'One at a time',d:'A queue.'}],
 rec:'A',why:'Three parallel Swift builds is about what a Mac does comfortably, and it limits how many token streams run at the same time. A setting lets you raise it.'},
{id:'K3',sec:'agents',title:'What happens when two tickets want the same files?',
 q:'',
 opts:[{k:'A',n:'Queue by default, offer Stack',d:'The later ticket waits. A button stacks both on one branch in order.'},{k:'B',n:'Always ask you',d:'A prompt every time.'},{k:'C',n:'Stack automatically',d:'One agent, one branch.'}],
 rec:'A',why:'Queueing is the safest default because the second ticket then builds on the first one\'s finished work. Stacking is faster but couples two tickets, so it should be a choice you make.'},
{id:'K4',sec:'agents',title:'How are agents named?',
 q:'',
 opts:[{k:'A',n:'By ticket: "Agent on #144"',d:'No persistent identity.'},{k:'B',n:'Agent 1, 2, 3',d:'Fixed slots.'}],
 rec:'A',why:'Agent sessions are temporary, and the ticket is the useful label. Slot numbers would suggest an identity that does not exist.'},
{id:'K5',sec:'agents',title:'Do you see token use?',
 q:'',
 opts:[{k:'A',n:'Per run, per ticket and per day',d:'Shown on the Agents screen and ticket sidebar.'},{k:'B',n:'Hidden',d:'Not shown.'}],
 rec:'A',why:'You said cost matters, and seeing which kinds of tickets are expensive is how you learn where to simplify.'},

/* ---------- L PROJECTS ---------- */
{id:'L1',sec:'projects',title:'How is a project set up?',
 q:'',
 opts:[{k:'A',n:'Settings screen that writes .hatch/project.json into the app repo',d:'Agents and CI can read it too.'},{k:'B',n:'Settings stored only in Hatch',d:'A database record.'},{k:'C',n:'Config file only',d:'No settings UI.'}],
 rec:'A',why:'You get a friendly screen, and the config is versioned and readable by any agent, even outside Hatch. The file can be committed with the code it describes.'},
{id:'L2',sec:'projects',title:'How is the area index created?',
 q:'The index maps each area to files and Spec IDs so agents read only the relevant part of a large app.',
 opts:[{k:'A',n:'An agent drafts it, you review',d:'On setup and on Re-scan.'},{k:'B',n:'You write it by hand',d:''}],
 rec:'A',why:'It is a one-time reading job that an agent does well and you can correct in minutes. The index is the biggest single saving in tokens per ticket.'},
{id:'L3',sec:'projects',title:'Where do Specs live?',
 q:'Today they are Swift code in Echo Labs.',
 opts:[{k:'A',n:'Markdown files in the project repo',d:'Under .hatch/spec/, indexed into SQLite for search.'},{k:'B',n:'Inside the Hatch database',d:'Edited in the app.'},{k:'C',n:'Stay as Swift',d:'Keep the current files.'}],
 rec:'A',why:'Plain text is searchable, readable by every agent and reviewable in a diff. Swift-encoded specs are hard to search and tie Hatch to the old code.'},
{id:'L4',sec:'projects',title:'What happens to the existing Echo Labs rounds?',
 q:'',
 opts:[{k:'A',n:'Import: decided rounds become Done and Decisions, open ones become Proposals',d:'Keeps history and your decisions.'},{k:'B',n:'Start fresh',d:'Old Echo Labs stays as an archive.'}],
 rec:'A',why:'Your decisions are the most valuable thing in Echo Labs, and the Spec depends on them. Open rounds continue in the new flow without being re-created.'},

/* ---------- M SYNC ---------- */
{id:'M1',sec:'sync',title:'Who wins when GitHub and Hatch disagree?',
 q:'',
 opts:[{k:'A',n:'Hatch owns status, GitHub owns text',d:'Edits to title, body and comments on GitHub are accepted. A hand-edited status label is flagged, not obeyed.'},{k:'B',n:'GitHub wins everything',d:'Always pull.'}],
 rec:'A',why:'Status transitions have rules (claims, checks) that live in Hatch. Text is free-form and benefits from editing on the phone. Flagging a changed label tells you without breaking the flow.'},
{id:'M2',sec:'sync',title:'What happens offline?',
 q:'',
 opts:[{k:'A',n:'Queue and retry with backoff',d:'A banner shows pending items. Nothing is lost.'},{k:'B',n:'Block changes',d:'Require a connection.'}],
 rec:'A',why:'Work should never stop because the network does. Every change is recorded in sync_log as pending first, so it survives a quit.'},
{id:'M3',sec:'sync',title:'Where are screenshots stored?',
 q:'GitHub\'s API does not support uploading images to issues.',
 opts:[{k:'A',n:'Committed to the private tickets repo',d:'attachments/<ticket>/. Linked from the issue.'},{k:'B',n:'Local only',d:'Not on GitHub.'}],
 rec:'A',why:'It keeps screenshots next to the ticket on every device and for cloud sessions, and it stays private. The cost is repo size, which is small for screenshots.'},
{id:'M4',sec:'sync',title:'How does search work?',
 q:'',
 opts:[{k:'A',n:'SQLite full-text over tickets, comments, Specs and decisions',d:'Behind Search (⌘K), instant and offline.'},{k:'B',n:'GitHub search',d:'Through the API.'}],
 rec:'A',why:'It is instant, offline and covers Specs and decisions that are not on GitHub. The same index feeds the free similar-ticket hints in the composer.'},

/* ---------- N LIBRARY ---------- */
{id:'N1',sec:'library',title:'What do Specs and Decisions look like?',
 q:'',
 opts:[{k:'A',n:'Specs by area with IDs and linked tickets, Decisions as read-only frozen results',d:'Each Decision links the ticket, picks and the Spec items it changed.'},{k:'B',n:'One combined Library',d:'Specs and Decisions together.'}],
 rec:'A',why:'A Spec says what is true now and a Decision says why. They change at different speeds, and keeping them apart is how Echo Labs already works.'},
{id:'N2',sec:'library',title:'What does the Log show?',
 q:'',
 opts:[{k:'A',n:'Every Hatch action with its GitHub sync result',d:'Filter by failed. Retry from the row.'},{k:'B',n:'Only errors',d:'A shorter list.'}],
 rec:'A',why:'You asked that syncs are recorded. A full log makes "did it reach GitHub" answerable in seconds, and errors are one filter away.'},
);
