DECISIONS.push(
/* ---------- H PROPOSAL STAGE ---------- */
{id:'H1',sec:'proposal',title:'Stage layout: where do controls, specimens and the decision sit?',
 q:'Try the prototype above. The old Rounds page had three fixed columns, which left the specimens the least room.',
 opts:[
  {k:'A',n:'Three fixed columns',d:'Controls left, specimens in the middle, decision right. Today\'s layout.',w:'three'},
  {k:'B',n:'Stage first, panels fold away',d:'Specimens get the width. Controls and Decision are side panels you can fold, open by default on wide windows and folded on narrow ones.',w:'stageFirst'},
  {k:'C',n:'Stacked',d:'Specimens on top, controls and decision below.',w:'stacked'}],
 rec:'B',why:'Judging is about looking, so the specimens should get the width. Folding panels gives you a full-width view when comparing and brings the controls back when tuning. The prototype has both panels so you can feel it. Three fixed columns waste space at 2 or 3 options, and stacking loses the view of the specimen while you decide.'},
{id:'H2',sec:'proposal',title:'How do you switch between specimens?',
 q:'Proposals have 2 to 5 options plus Echo today.',
 opts:[
  {k:'A',n:'All side by side, solo button on each',d:'Everything visible, and a button shows one large. This is today\'s behaviour.',w:'grid3'},
  {k:'B',n:'Tabs, one at a time',d:'Select an option, flip back and forth with a key.',w:'tabs'},
  {k:'C',n:'Adaptive: side by side up to three, filmstrip beyond',d:'With 4 or more, a filmstrip of thumbnails at the bottom and two shown large. Space always flips with Echo today.',w:'filmstrip'}],
 rec:'C',why:'Side by side is the best way to compare, until it gets too narrow to judge. At four or five options a filmstrip keeps every option one click away while two stay large. Space as a flip key means you can always check an option against Echo today without moving the mouse.'},
{id:'H3',sec:'proposal',title:'Which compare modes exist?',
 q:'Try each one in the prototype: Side by side, Overlay, Flip, Wipe, Matrix.',
 opts:[
  {k:'A',n:'Side by side only',d:'Simple, as today.',w:'grid3'},
  {k:'B',n:'Side by side, Overlay, Flip, Wipe',d:'Four ways to compare one option against Echo today.',w:'overlay'},
  {k:'C',n:'All four plus Matrix',d:'Matrix shows every scenario for every option in a grid.',w:'cards'}],
 rec:'C',why:'Different differences show up in different modes: Flip reveals small shifts, Wipe shows alignment, Overlay shows spacing, and Matrix shows what changes across states. They are cheap to build because the specimens are the same views, only arranged differently. The default stays Side by side.'},
{id:'H4',sec:'proposal',title:'How is Echo today shown?',
 q:'Every proposal is judged against how Echo looks now.',
 opts:[
  {k:'A',n:'A pinned specimen with a Match badge',d:'First in the list. A badge says when it was last checked against the real Echo, and warns if Echo changed since.'},
  {k:'B',n:'A screenshot of the real Echo',d:'Captured from the running Echo for each scenario.'},
  {k:'C',n:'Not shown',d:'Judge on the options alone.'}],
 rec:'A',why:'A specimen can be switched across scenarios, appearances and zoom, which a screenshot cannot. The Match badge keeps it honest: if Echo changed after the specimen was written, you see a warning instead of judging against stale ground. The real-Echo screenshot remains available in the Match check after build.'},
{id:'H5',sec:'proposal',title:'How are scenarios (states) tested?',
 q:'This is the part of the old page that was hardest to use.',
 opts:[
  {k:'A',n:'Scenario strip',d:'Named states in a row, one click each. Applies to all specimens at once.'},
  {k:'B',n:'Strip plus Matrix view',d:'The strip, and a grid of every scenario by every option for spotting differences.'},
  {k:'C',n:'Controls panel only',d:'States are knobs among the other controls.'}],
 rec:'B',why:'The strip answers "how does it look when it errors". The Matrix answers "where do my options differ across all states", and flags the cells that differ from Echo today. Having states as knobs hides them among tuning controls and makes you set them one by one on each specimen.'},
{id:'H6',sec:'proposal',title:'Which scenarios must every Proposal include?',
 q:'The agent decides what to test unless there is a standard set.',
 opts:[
  {k:'A',n:'A standard set, extendable',d:'Rest, Hover, Pressed, Focus, Disabled, Empty, Error, Long text, Many items, Loading. A Proposal marks a state as not applicable with a reason.'},
  {k:'B',n:'The agent chooses',d:'Whatever seems relevant.'},
  {k:'C',n:'A short set',d:'Rest, Hover, Error.'}],
 rec:'A',why:'Most regressions live in the states nobody looked at, such as long text or empty. A standard set makes them part of every judgment, and the "not applicable, because" note makes skipping a deliberate choice. Hatch checks this in code (see the quality gate).'},
{id:'H7',sec:'proposal',title:'Appearance controls: what and where?',
 q:'',
 opts:[
  {k:'A',n:'Always-visible bar: appearance, contrast, corners, text size, motion',d:'Light, Dark, Increase Contrast; Corners 10 or 26; text size; Reduce Motion. Applies to all specimens, remembered per ticket.'},
  {k:'B',n:'A menu in the toolbar',d:'Hidden behind one button.'},
  {k:'C',n:'Show all appearances at once',d:'Each specimen rendered in light and dark together.'}],
 rec:'A',why:'You check light and dark constantly, and Corners 10 versus 26 matters in Echo, so these must be one click. A bar that is always visible makes them part of every look. A "both at once" toggle can be offered from the same bar, but doubling every specimen all the time costs width.'},
{id:'H8',sec:'proposal',title:'Measurements: how do you see exact spacing and sizes?',
 q:'Turn on Redlines in the prototype.',
 opts:[
  {k:'A',n:'Redlines overlay',d:'A toggle draws padding, gaps and sizes on the specimens in the specimen\'s units.'},
  {k:'B',n:'A measurements table',d:'Numbers listed beside the specimens.'},
  {k:'C',n:'None',d:'Judge by eye.'}],
 rec:'A',why:'Spacing is the thing you keep deciding, and numbers drawn on the specimen tie each value to the place it applies. It is also the same data the Match check compares afterwards, so the specimens already know their measurements. A table can come later as a detail view.'},
{id:'H9',sec:'proposal',title:'Zoom and sizing',
 q:'Specimens have a real design size.',
 opts:[
  {k:'A',n:'100% means Echo\'s real size, fit when too wide, with a label',d:'Zoom steps up to 200%. A note says when a specimen is scaled down.'},
  {k:'B',n:'Always fit to the available width',d:'Specimens scale to the window.'}],
 rec:'A',why:'You judge spacing and type at their real size, and scaling by stealth would make 12pt look like 9pt without telling you. Fit-to-width is still one click for overview.'},
{id:'H10',sec:'proposal',title:'Controls panel: how are the knobs organized?',
 q:'',
 opts:[
  {k:'A',n:'Decision controls first, Playground folded, presets on top',d:'Controls with a question come first with the recommended star. Knobs without a question are in a folded Playground. A Recommended preset sets everything.'},
  {k:'B',n:'One flat list',d:'All controls together.'},
  {k:'C',n:'No controls',d:'Only fixed options.'}],
 rec:'A',why:'Controls with a question are the decision, and playground knobs like speed are not. Keeping them apart stops a speed slider looking like a design question. The Recommended preset lets you try my whole answer in one click.'},
{id:'H11',sec:'proposal',title:'The decision panel',
 q:'Today: one card per question with a recommendation, reason, radio choices and a note.',
 opts:[
  {k:'A',n:'Keep the card per question, add "Use recommendation" and "Use what\'s in preview"',d:'Every card shows what I recommend and why. Bottom: Accept or Send back.'},
  {k:'B',n:'Single choice',d:'Choose one option as a whole, no per-question answers.'},
  {k:'C',n:'Ranking',d:'Order the options by preference.'}],
 rec:'A',why:'Your decisions are rarely "all of B". You choose the spacing from one and the placement from another, and per-question answers capture that. The recommendation with its reason is a requirement you set, so it is part of every card.'},
{id:'H12',sec:'proposal',title:'Verdicts on options',
 q:'',
 opts:[
  {k:'A',n:'Pick, Maybe, No on each option, plus a note',d:'Shown on the specimen header (see prototype) and summarized in the decision panel.'},
  {k:'B',n:'Pick only',d:'One selected option.'},
  {k:'C',n:'Star rating',d:'1 to 5.'}],
 rec:'A',why:'"Maybe" is the verdict that tells the agent what to keep refining, and "No" tells it what not to bring back. Both are lost with pick-only. It already works this way in Echo Labs.'},
{id:'H13',sec:'proposal',title:'Notes on the stage',
 q:'A note should say what you were looking at.',
 opts:[
  {k:'A',n:'Pin a note on the specimen',d:'Click a spot to drop a pin. It stores the scenario, appearance, corners and zoom you had on. Also notes per option, per question and general.'},
  {k:'B',n:'Text notes only',d:'No position.'}],
 rec:'A',why:'"Spacing too tight" means something different in dark mode with Large text than in light. A pin that records the state it was written in lets the agent reproduce what you saw, and re-opens the stage in that state when you click it.'},
{id:'H14',sec:'proposal',title:'Asking a question while judging',
 q:'',
 opts:[
  {k:'A',n:'Ask button in the stage toolbar',d:'Sends your question with a picture of the current view and the state. The answer arrives in the thread and in the Ask panel.'},
  {k:'B',n:'Ask through the thread only',d:'Leave the stage to write.'}],
 rec:'A',why:'The question is usually about what you are looking at. Sending the current view and state with it means the agent sees what you see, with no explanation needed.'},
{id:'H15',sec:'proposal',title:'Revisions after you send it back',
 q:'',
 opts:[
  {k:'A',n:'Keep old options, mark new ones, revision switcher, compare revisions',d:'NEW badges, a "New since your last review" summary, and a way to view revision 1 or overlay 1 on 2.'},
  {k:'B',n:'Only the latest',d:'Replace the options.'}],
 rec:'A',why:'It keeps the existing rule that old options are never removed, because your earlier picks refer to them. Overlaying revisions shows exactly what changed.'},
{id:'H16',sec:'proposal',title:'What happens when you press Accept?',
 q:'Accepting starts an agent run that costs tokens.',
 opts:[
  {k:'A',n:'A confirmation sheet',d:'Lists your choices, the repos and branches that will change, the tests that will run and a token estimate. Then Accept.'},
  {k:'B',n:'Immediate',d:'Accept and start.'}],
 rec:'A',why:'Accept starts work and spends money, so it is the one place worth one more look. The sheet is also where you notice that the wrong repo or branch is selected.'},
{id:'H17',sec:'proposal',title:'What happens when you press Send back?',
 q:'',
 opts:[
  {k:'A',n:'Choose a reason, then write what to change',d:'Needs more options, Change an option, or Different direction. A note is required.'},
  {k:'B',n:'Free note only',d:'Write whatever you like.'}],
 rec:'A',why:'The reason picks what the agent does: add options and keep the old ones, edit one option, or start from a new angle. Saying so in a field is faster and less error-prone than expecting the agent to infer it from prose.'},
{id:'H18',sec:'proposal',title:'How are animated specimens judged?',
 q:'Toasts, sheets and transitions move.',
 opts:[
  {k:'A',n:'Transport bar',d:'Play, scrub, step one frame, speed 0.25x to 2x, loop, and Reduce Motion preview. The timeline of tagged parts is drawn under it.'},
  {k:'B',n:'Play button only',d:'Plays at normal speed.'}],
 rec:'A',why:'Motion decisions are about timing you cannot judge at 1x, such as when the toast goes away. Scrubbing and slow speed let you see it, and the timeline is the same data the Match check compares against Echo afterwards.'},
{id:'H19',sec:'proposal',title:'A quality gate before a Proposal reaches you',
 q:'',
 opts:[
  {k:'A',n:'Hatch validates the Proposal in code on hatch offer',d:'Echo today present, standard scenarios covered or marked not applicable, every question has a recommendation and reason, specimens render, design sizes set. If not, it goes back to the agent.'},
  {k:'B',n:'The agent follows the guide',d:'As HOW_TO_WRITE_A_ROUND.md today.'}],
 rec:'A',why:'This is your rule of doing as much as possible in code. A missing recommendation is currently an assertion that fails in the app, after the agent has finished. The gate catches it while the agent can still fix it, and you never see a half-finished Proposal.'},
{id:'H20',sec:'proposal',title:'Keyboard on the stage',
 q:'',
 opts:[
  {k:'A',n:'Full map',d:'Space flip, ← → switch specimen, 1–5 compare modes, L/D light and dark, R redlines, S scenario next, ⌘↩ Accept, ⌘⇧↩ Send back. A help overlay on ?'},
  {k:'B',n:'Mouse only',d:'No shortcuts.'}],
 rec:'A',why:'You will switch and compare hundreds of times. The shortcuts are single keys, and ⌘↩ for Accept can be a confirm sheet (see above), so a stray key never starts a build.'},
{id:'H21',sec:'proposal',title:'When a specimen fails or is out of date',
 q:'',
 opts:[
  {k:'A',n:'Show the failure on the specimen',d:'A clear message in the place of the specimen, a button to report it to the agent, and the rest of the stage keeps working. A banner says when a specimen is older than the latest code.'},
  {k:'B',n:'Blank or crash',d:'Whatever the code does.'}],
 rec:'A',why:'One broken specimen must not stop you judging the others. The report button turns the failure into an instruction to the agent.'},
);
